=== sm-pkg/plugins/schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/leighmacdonald/smpkg-repo/refs/heads/master/schema.json",
  "title": "smpkg package definition",
  "type": "object",
  "properties": {
    "name": {
      "type": "string",
      "description": "The name of the package"
    },
    "homepage": {
      "type": "string",
      "description": "The homepage of the package"
    },
    "description": {
      "type": "string",
      "description": "Package description"
    },
    "license": {
      "type": "string",
      "description": "The license of the plugin"
    },
    "version": {
      "type": "string",
      "description": "The version of the package"
    },
    "inputs": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "The input files for the package"
      }
    },
    "authors": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "List of authors"
      }
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "string",
        "description": "List of dependencies"
      }
    }
  },
  "required": ["name", "description", "version"]
}

=== sm-pkg/plugins/halloween_cosmetic_enabler/plugin.json
{
  "$schema": "https://raw.githubusercontent.com/sm-pkg/sm-pkg/refs/heads/master/schema/plugin.json",
  "name": "halloween_cosmetic_enabler",
  "description": "Protects players with reserve slot from being autokicked",
  "authors": ["Mikusch"],
  "homepage": "https://github.com/Mikusch/HalloweenCosmeticEnabler",
  "inputs": ["hwn_cosmetic_enabler.sp"],
  "version": "1.3.1"
}

=== sm-pkg/plugins/sm_hidehud/plugin.json
{
  "$schema": "https://raw.githubusercontent.com/sm-pkg/sm-pkg/refs/heads/master/schema/plugin.json",
  "name": "disableautokick",
  "description": "Hides a players HUD",
  "homepage": "https://github.com/MoonlyDays",
  "authors": ["Moonly Days"],
  "inputs": ["sm_hidehud.sp"],
  "version": "1.0.0"
}
